### ISSUE TITLE
How to test jobs using meteortesting:mocha and chai?

### ISSUE THREAD

**Issue by mexin** [SimonSimCity/meteor-job-collection#3]
Hello Simon

I've been struggling on how to add test suites for our jobs in a big app we are building, wondering if there is a simple way to test them. 

Right now I'm stuck doing a integration test of a function that invokes several chained (using job.depends) jobs, seems the first job stays on "ready" all the time no matter if I try to wait for it, seems it never executes the processJobs callback.

Any help or insight will be highly appreciated.

Thank you!

**Comment by SimonSimCity** [comment]
Well, when thinking about this, you shouldn't test the chaining itself. I personally take the code, executed in a job, as an exportable function and test it. If I would have several chained jobs, I would take each part and test it as one individual unit. The combination then has to work like in a micro-service environment.

Imagine, you have a ton of several applications - each of them in your case is a job, happen to be written in the same language and framework - but this could also be different, right? At least when thinking of it as micro-services. You'd then try a superrior unit to test this. This could be done by having your application running in a production-like environment and testing the outcome on the UI, which is what we're doing. A useful tools for this is [Chimpy](https://thebrainfamily.github.io/chimpy/) which also has a special meteor integration.

Hope this helps.
